name: novel_reader
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  mmkv: ^1.3.0
  shared_preferences: ^2.2.0
  get_it: ^7.6.0
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  file_picker: ^5.3.3
  flutter_native_splash: ^2.3.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fixnum: ^1.1.0
  uuid: ^3.0.7
  darq: ^2.0.0
  auto_route: ^7.8.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_lint: ^1.4.0
  riverpod_generator: ^2.2.4
  icons_launcher: ^2.1.3
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.0
  
flutter:
  uses-material-design: true
